---
- hosts: localhost
  tasks:
    - name: Load state from file
      include_vars:
        file: "{{ state_file_path }}"
        name: tenks_state

- hosts: hypervisors
  vars:
    physnet_indices: >-
      {{ hostvars.localhost.tenks_state[inventory_hostname].physnet_indices }}
  tasks:
    - include_tasks: hypervisor_setup.yml

- hosts: libvirt
  vars:
    nodes: >-
      {{ hostvars.localhost.tenks_state[inventory_hostname].nodes
           | default([]) }}
    libvirt_enable_efi_default: "{{ 'efi' in (nodes | map(attribute='boot_firmware') | map('lower')) }}"
  tasks:
    - block:
        - name: Configure host for Libvirt
          include_role:
            name: stackhpc.libvirt-host
          vars:
            libvirt_host_pools:
              - name: "{{ libvirt_pool_name }}"
                type: "{{ libvirt_pool_type }}"
                capacity: "{{ libvirt_pool_capacity }}"
                path: "{{ libvirt_pool_path }}"
                mode: "{{ libvirt_pool_mode }}"
                owner: "{{ libvirt_pool_owner }}"
                group: "{{ libvirt_pool_group }}"
            libvirt_host_require_vt: "{{ libvirt_require_vt }}"
            libvirt_host_enable_efi_support: "{{ libvirt_enable_efi | default(libvirt_enable_efi_default) }}"

        - name: Set up Virtual BMC daemon
          include_role:
            name: virtualbmc-daemon
          vars:
            vbmcd_virtualenv_path: "{{ virtualenv_path }}"
            vbmcd_python_upper_constraints_url: >-
              {{ python_upper_constraints_url }}

      when: cmd == 'deploy'
